export enum CampaignObjective {
    OUTCOME_SALES = 'OUTCOME_SALES',
    OUTCOME_LEADS = 'OUTCOME_LEADS',
    OUTCOME_AWARENESS = 'OUTCOME_AWARENESS',
    OUTCOME_TRAFFIC = 'OUTCOME_TRAFFIC',
    OUTCOME_ENGAGEMENT = 'OUTCOME_ENGAGEMENT',
    OUTCOME_APP_PROMOTION = 'OUTCOME_APP_PROMOTION'
}
